=== AtefBN/errata-esdoc-ws/errata/handlers/schemas/retrieve.json
{
    "$schema": "http://json-schema.org/schema#",
    "additionalProperties": false,
    "properties": {
        "closed_at": {
            "format": "date-time",
            "type": "string"
        },
        "created_at": {
            "format": "date-time",
            "type": "string"
        },
        "description": {
            "minLength": 1,
            "type": "string"
        },
        "id": {
            "pattern": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
            "type": "string"
        },
        "institute": {
            "minLength": 1,
            "type": "string"
        },
        "last_updated_at": {
            "format": "date-time",
            "type": "string"
        },
        "materials": {
            "items": {
                "pattern": "\\.(jpg|gif|png|tiff)$",
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        },
        "models": {
            "items": {
                "minLength": 1,
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        },
        "number": {
            "minimum": 0,
            "type": "integer"
        },
        "project": {
            "minLength": 1,
            "type": "string"
        },
        "severity": {
            "enum": [
                "Low",
                "Medium",
                "High",
                "Critical"
            ],
            "type": "string"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "url": {
            "minLength": 1,
            "type": "string"
        },
        "workflow": {
            "enum": [
                "New",
                "On hold",
                "Wontfix",
                "Resolved"
            ],
            "type": "string"
        }
    },
    "required": [
        "number",
        "id",
        "title",
        "description",
        "severity",
        "project",
        "models",
        "institute",
        "workflow",
        "created_at",
        "last_updated_at"
    ],
    "title": "ESGF issue JSON schema",
    "type": "object"
}

=== AtefBN/errata-esdoc-ws/test-data/issue-6.json
{
"institute": "IPSL", 
"number": 1, 
"id": "96eba87b-2f6d-4eea-a474-3f5c9dff6675", 
"title": "Wrong pH computing", 
"description": "Oceans (PISCES) the hydrogen ion (H+) concentration instead of pH. pH variable has to be computed as follows: pH = -log10[H+].", 
"project": "CMIP5", 
"models": [
"IPSL-CM5A-LR"
], 
"severity": "High", 
"url": "http://errata.ipsl.upmc.fr/issue/2", 
"materials": [
"http://errata.ipsl.upmc.fr/static/images_errata/time.jpg", 
"http://errata.ipsl.upmc.fr/static/images_errata/time5.jpg"
], 
"workflow": "New", 
"created_at": "2016-05-25T09:12:31+00:00", 
"last_updated_at": "2016-05-25T09:12:31+00:00"
}
